{% set name = "icechart" %}
{% set version = "0.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: df624f35dcb29313cce245d60baa0035d932c29323fa3da50aa8a2769d9af48d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - earthengine-api
    - folium
    - ipyleaflet
    - pyshp
    - python >=3.6

test:
  imports:
    - icechart

about:
  home: "https://github.com/Surfix/icechart"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A python package for icesat data analysis"
  doc_url: https://Surfix.github.io/icechart
  dev_url: https://github.com/Surfix/icechart

extra:
  recipe-maintainers:
    - Surfix
